---
- name: installig vim & jq 
  hosts: localhost
  become: yes
  vars:
    packages: ["vim","jq"]
    username: "{{ hostname }}"
    hostname: "{{ ansible_hostname }}"
    current_date: "{{ ansible_date_time.date }}"
    filename: "user.txt"
  tasks:
    - name: installing packages on ubuntu machine 
      ansible.builtin.apt:
        name: "{{packages}}"
        state: present
        update_cache: yes
    - name: Create file from template
      ansible.builtin.template:
        src: template/user.txt.j2
        dest: "/home/{{ filename }}"
      become: true
    - name: display file content
      ansible.builtin.command:
        cmd: "cat /home/{{ filename }}"
      register: file_content
    - name: show content
      ansible.builtin.debug:
        var: file_content.stdout_lines
        